### ISSUE TITLE
could not compile `swc_ecma_ast`

### ISSUE THREAD

**Issue by aresbit** [UltiRequiem/react-run#9]
the method `eq_ignore_span` exists for reference `&num_bigint::BigInt`, but its trait bounds were not satisfied
   --> C:\Users\aresyang\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\swc_ecma_ast-0.65.4\src\lit.rs:66:20
    |
66  | #[derive(Eq, Hash, EqIgnoreSpan)]
    |                    ^^^^^^^^^^^^ method cannot be called on `&num_bigint::BigInt` due to unsatisfied trait bounds
    |
   ::: C:\Users\aresyang\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\num-bigint-0.2.6\src\bigint.rs:115:1
    |
115 | pub struct BigInt {
    | ----------------- doesn't satisfy `num_bigint::BigInt: EqIgnoreSpan`
    |
    = note: the following trait bounds were not satisfied:
            `num_bigint::BigInt: EqIgnoreSpan`
            which is required by `&num_bigint::BigInt: EqIgnoreSpan`
    = note: this error originates in the derive macro `EqIgnoreSpan` (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by UltiRequiem** [comment]
Thanks, will check it out!

**Comment by aresbit** [comment]
aha, waiting for your good news， bro

> Thanks, will check it out!

**Comment by UltiRequiem** [comment]
Should be working now, thanks for the report and sorry for the long waiting!

**Comment by aresbit** [comment]
can not work, problem as the same

**Comment by aresbit** [comment]
maybe I should try .exe file
